### ISSUE TITLE
Android services that need fixed

### ISSUE THREAD

**Issue by piggz** [sailfish-on-fxtecpro1/droid-config-t5#10]
vendor.dataqti
vendor.imsrcsservice
vendor.ims_rtp_daemon

**Comment by piggz** [comment]
only dataqti is failing in new build

**Comment by piggz** [comment]
reason for failure is missing /dev/rmnet_ctrl

**Comment by Michal-Szczepaniak** [comment]
Fixed…ish?

**Comment by 0312birdzhang** [comment]
Hi piggz, davinci has the same issue, services crash and no `/dev/rmnet_ctrl`, any tips how to resolve it?

**Comment by piggz** [comment]
> Hi piggz, davinci has the same issue, services crash and no `/dev/rmnet_ctrl`, any tips how to resolve it?

Have you tried disabling it and using dummy_netd?

**Comment by 0312birdzhang** [comment]
Thank you, it's working 👍
