### ISSUE TITLE
Can't get mobile data to work

### ISSUE THREAD

**Issue by popanz** [sailfish-on-fxtecpro1/droid-config-t5#19]
Settings are identically to that on my XperiaX. but I just get the error message Simcard not active. The issue seems to be different from the closed one. There are no visible connection attempts.

**Comment by NotKit** [comment]
Please check if the issue still persists after updating packages by:
```zypper ref
zypper update```
It should install jolla-settings-networking-multisim among the others.

**Comment by popanz** [comment]
Mobile data is working now. Thanx!
