### ISSUE TITLE
front camera not working

### ISSUE THREAD

**Issue by popanz** [sailfish-on-fxtecpro1/droid-config-t5#21]

**Comment by NotKit** [comment]
Does it work in https://openrepos.net/content/piggz/advanced-camera? If yes, it is probably a configuration issue on our side.

**Comment by popanz** [comment]
WIth advanced camera both cameras work.

**Comment by piggz** [comment]
Well, advanced-camera is the one true sfos camera app! :D

**Comment by Kabouik** [comment]
I confirm only one camera works with the default application, and both work in Advanced Camera. However, there are no options for flash and ISO settings (same for both cameras).

**Comment by Kabouik** [comment]
ISO settings do work correctly in the official camera app, just not in Advanced camera.

Also, pictures taken with Advanced camera are upside down, probably just some rotation information to fix in the EXIF.

**Comment by eLtMosen** [comment]
> Well, advanced-camera is the one true sfos camera app! :D

Only too true and thanks for your work again!
To harden the "true camera app" status, it would be great to have Advanced Camera assigned to the camera button for startup as well as shooting photos :)
Should i open a new issue or can this be discussed/noted here?
