### ISSUE TITLE
No Alt+Tab, but something similar existed for the TOHKBD

### ISSUE THREAD

**Issue by Kabouik** [sailfish-on-fxtecpro1/droid-config-t5#23]
Alt+Tab does nothing on SFOS, but I remember [Kimmoli](https://openrepos.net/user/826/programs) coded something that made it work with the TOHKBD. It was installed automatically when plugging the TOHKBD on the Jolla, no manual installation from OpenRepos. Unfortunately I am not sure whether Kimmoli is still active as a Sailfish developer.

**Comment by piggz** [comment]
You'll be wanting my app just for this! https://openrepos.net/content/piggz/taskswitcher

**Comment by Kabouik** [comment]
I love it! However it would be nice to add a setting to use Ctrl+Tab instead of Alt+Tab, since Alt is only on the left of the Pro¹ keyboard, and therefore the combination is rather difficult to do. Also, reverse cycle order with Shift?

**Comment by Kabouik** [comment]
Not a problem with the port, I think (although it would be useful to confirm), so I am not reopening the issue, but there seems to be an issue with the apps that Taskswitcher sees open and the actually open apps, see screenshot below:

![Screenshot_20191220_001](https://user-images.githubusercontent.com/7107523/71225551-e80e1380-22d0-11ea-9158-2b5760d64a93.png)

Selecting with Taskswitcher the icon of an app not currently open will immediately open it.
