### ISSUE TITLE
Connectivity issues

### ISSUE THREAD

**Issue by Kabouik** [sailfish-on-fxtecpro1/droid-config-t5#26]
Probably something related to my provider, since issue #12 shows that it should be possible to call.

**Comment by Kabouik** [comment]
Works after a reboot, sorry for the noise.

**Comment by Kabouik** [comment]
Reopening because this seems to happen very frequently. I'm in 4.2.1.20.

**Comment by Kabouik** [comment]
Reboot usually fixes the issue, but restarting network interfaces using sailfish-utilities does not.

**Comment by Kabouik** [comment]
I am getting this issue more and more lately, to the point that it is actually rare that I can give a call. SMS sending and reception are also greatly impacted: as I type, I received a text that was sent to me 5 hours ago despite stable network coverage in my place. 

Below are the ofono logs during a call attempt: 
[ofono_2019-12-31_182946.tar.gz](https://github.com/sailfish-on-fxtecpro1/droid-config-t5/files/4015899/ofono_2019-12-31_182946.tar.gz)

**Comment by Kabouik** [comment]
May or may not be related, someone using Android said this on Discord:

> [18:00] ravelo: anyone experienced this problem:
> [18:01] ravelo: it happens quite often that i get called and am not available for the caller
> [18:02] ravelo: i now changed netwotk settinngs to lte/gsm
> [18:02] ravelo: looks better
> [18:02] ravelo: now
> [18:03] ravelo: i am in europe so i only need gsm 3g 4g
> [18:05] ravelo: LTE tdscdma GSM i am using now
> [18:09] ksalcido95: Try LTE/UMTS, that's what I use for LTE and GSM here in the US
> [18:43] ravelo: No UMTS available in the settings
> [18:44] ravelo: Maybe its called differently
> [18:45] ravelo: I have qwertz layout
> [19:44] ksalcido95: Try with the dialer code
>  *#*#4636#*#* 
> [19:56] ravelo: @ksalcido95 , i should try this Code?
> [20:01] ksalcido95: In the dialer yes, then you'll see a menu, select phone information and you can scroll down to where it should say LTE/WCDMA or something along those lines
> [20:25] ravelo: OK, Changed to LTE wcdma
> [21:01] ksalcido95: You can alter the settings to meet your needs should the need arise :slight_smile:
> [21:06] ravelo: GSM is missing
> [21:06] ravelo: LTE UMTS and GSM is not possible
> [21:07] ksalcido95: Oh, my apologies :slight_frown:
> [21:07] ravelo: Maybe is sufficient Like that
> [21:07] ravelo: Not your fault of course
> [21:08] ravelo: The Phone does Not offer this option
> [21:09] ravelo: I Put LTE UMTS Auto (PRL)

If I can try something similar on SFOS, I will. I am in Europe too by the way.

**Comment by Kabouik** [comment]
There was a bad FPC connection between the USB PCB and the main board of my phone. I fixed it, which immediately fixed other issues I was experiencing with modules tied to the USB board: no microphone input, no hall sensor (and hence no virtual keyboard), and perhaps (to be confirmed) unreliable USB charging.

There is a possibility that this was also causing my GSM/3G/4G instability:

![image](https://user-images.githubusercontent.com/7107523/72846855-b0183880-3ca1-11ea-9650-6702c599a86d.png)

Time will tell, I'll use my phone normally for a few days and see if the issue is fixed (fingers crossed).

**Comment by Kabouik** [comment]
I am still experiencing this issue, unfortunately.

**Comment by Kabouik** [comment]
After a few days of use, I can confirm this issue happens everyday, and in fact most of the time. There are only very rare moments when I can initiate or receive a call, or send or receive a sms.

Of note, data and GSM icons are unusually often off (in areas where I know there is very good coverage). However, even when they are on, most of the time I still cannot call or text, so somehow the icons are not representative of whether I can use the network.

If I don't move or do anything, the status can change: icons can show up or hide, sometimes in parallel with actual connection to mobile networks, most of the times still with no connection.

Toggling flight mode on and off sometimes work, bust most of the times do not. Same with Sailfish Utilities > Reset Network. Reboot works more often, but it still is far from being a reliable solution and most of the times I still cannot call or text after reboot. Usually when I use one of those three methods, the icons come back relatively fast, but eventually turn off very soon, and may or may not come back in the next minutes.

If I move out of a building, it seems that connection improves a bit (as I can sometimes initiate a call when I could not before, even though icons were displayed in both locations), but it is hard to tell because all of the above is so hard to reproduce in a predictable way. 

At this point I am not sure whether it is a software or a hardware issue. Ideas are welcome, so that I can contact F(x)tec and ask for servicing the phone if it turns out to be hardware. My best bet will probably be to restore Android and test, but maybe there is something else I can do to debug in SFOS (in addition to ofono logs, but I don't know how to review them myself).

**Comment by Kabouik** [comment]
I forgot to report it here, but I was having similar issues after restoring Android for testing. However, I think it was a little less frequent, so maybe it's an hardware issue that is somehow less efficiently mitigated in SFOS? 

Additionally, mobile network issues seem to occur a lot more frequently under 3G coverage, 2G and 4G seem to work better (but not perfectly).

**Comment by piggz** [comment]
Is this still an issue for you?  Im not experiencing such things, have you contacted fxtec about it?

**Comment by Kabouik** [comment]
It is still an issue for me but I am currently trying another device, hopefully I can finally tell if that was a hardware issue. I'll report back when I'm done.

**Comment by Kabouik** [comment]
It's better with the new device because once the signal is caught, as it is not lost as easily as with the older phone. This might be due to a small copper-coloured metal part missing in the hinge of the older phone. However, acquiring the signal is still very long and difficult. I've been sitting by the window for a good 10 minutes and still have no network.

In Ofono log, I noticed lines reading "drivers/ril/ril_cell_info.c: ril_cell_info_parse_cell_wcdma() [wcdma] reg=0, psc=441, strength=0, err=99`. Sometimes, there's `strength=1` but it seems `strengh=0` occurs more often, and I'm wondering about this `err=99`. Is this expected?

I tried the same SIM card in a Jolla C and have no such issues in the same spots (home, work): the signal is acquired almost immediately after the SIM is inserted. Someone else with a Pro¹ running SFOS and the same operator also reported he has no connectivity issues.

**Comment by Kabouik** [comment]
Airplane mode on/off didn't help with the above issue, but reboot did. I also observed on the previous phone that reboot tended to fix it more often than airplane on/off, although it was far from working all the time.

Is that possible that, when the connection unstable, SFOS fails to correctly resume on it until rebooted? WIth the hardware fault of my previous device (a missing metal part), it is possible that the reception was more unstable than usual, and always ended up in a failure state where SFOS would fail to restore it. What do you think?

**Comment by Kabouik** [comment]
I was out just now and can confirm mobile network is working much better with the new device, at least for Internet. I was able to browse the Internet, which was never possible with the other phones in more than 6 months of use (even when the 2G/3G/4G icons were showing, it was too unstable to be usable).

Therefore, this was most likely a hardware issue, but the message above might need some further investigation because I think it's weird that the connection is so hard to get back once the signal has been lost temporarily.
