### ISSUE TITLE
Fingerprint support

### ISSUE THREAD

**Issue by CODeRUS** [sailfish-on-fxtecpro1/droid-config-t5#29]

**Comment by Michal-Szczepaniak** [comment]
With jolla closed source fingerprint software i doubt it's anywhere near doable? Or something changed?

**Comment by piggz** [comment]
Well, there is a dbus api that needs to be implemented, abrnason mentioned it to me once ... a bit of work though!

**Comment by Kabouik** [comment]
Nice to hear that there is some hope for the longer term.

**Comment by piggz** [comment]
At the last community meeting, there was talk of jolla enabling this soon (tm)!

**Comment by piggz** [comment]
This is now fixed with sailfish-fpd-community
