### ISSUE TITLE
Device encryption

### ISSUE THREAD

**Issue by schmittlauch** [sailfish-on-fxtecpro1/droid-config-t5#35]
At least all Xperia Sailfish X devices now officially support device encryption. While only the Xperia 10 image enables encryption already at first boot, all other Xperia devices have the option of enabling encryption afterwards at the expense of deleting all user data.

As the code should be mostly upstreamed, what is the effort required for getting encryption working for this device as well?

**Comment by piggz** [comment]
This is fixed in 3.4
